### ISSUE TITLE
the  difference between the direct 3*3 sRGB2XYZ matrix

### ISSUE THREAD

**Issue by JuZiSYJ** [mahmoudnafifi/CIE_XYZ_NET#3]
Hello，i hava some questions：
1.Why not using direct 3*3 sRGB2XYZ matrix directly，which is [[3.24..,-1.5,...]]?
2.The model -produced  XYZ image  is not the same with directly using the 3*3 sRGB2XYZ matrix

**Comment by mahmoudnafifi** [comment]
Hi,
Theoretically, the process to go from raw to sRGB is as follows: raw -> XYZ -> RGB -> gamma operation -> sRGB. Then, to go back from sRGB to XYZ (as you said), it is a simple degamma operation followed by mapping from RGB to XYZ using the sRGB2XYZ matrix. However, cameras do not follow this flow to go from raw to sRGB and there are additional operations included to go from the RGB (or XYZ) to the final sRGB image. Thus, the standard operation doesn't actually reconstruct the scene-referred XYZ (i.e., the corresponding XYZ values to what was captured by the camera), but it maps to the display-referred XYZ values (i.e., the corresponding XYZ values to what you see in your display). Low-level computer vision algorithms usually work better if they have some knowledge about the scene-referred values. That is the key behinds the paper and that is why we got better results compared to using the standard conversion.
