### ISSUE TITLE
Training code, dataset availability?

### ISSUE THREAD

**Issue by zachlewis** [mahmoudnafifi/CIE_XYZ_NET#4]
Hey Mahmoud,

Nice work! This is super inspiring.

Do you still have plans to share the training code and the dataset?

**Comment by mahmoudnafifi** [comment]
Thanks for your interest.
The paper is under review. We will release training code and dataset upon acceptance.

**Comment by mahmoudnafifi** [comment]
Training code and dataset are now available.

**Comment by zachlewis** [comment]
Thank you. Congratulations on getting accepted!

**Comment by mahmoudnafifi** [comment]
It hasn't been accepted yet, but I felt it is too much to wait 😃

**Comment by zachlewis** [comment]
Well, greatly appreciated either way. Thanks again, and good luck!
