### ISSUE TITLE
Does the XYZ color space apply to some image retouching operations, such as Hue or Saturation adjustments?

### ISSUE THREAD

**Issue by a2108870** [mahmoudnafifi/CIE_XYZ_NET#6]
Hi, thank you for your great work. I have been studying image retouching recently, which usually involves using rawRGB images. I am wondering if the XYZ color space is also suitable for some image retouching operations. For example, when I want to modify the Hue of an image, I would convert the image to the HSV color space and then adjust the H channel. However, I am not sure if the general RGB-to-HSV conversion formula is applicable in the XYZ color space.

**Comment by mahmoudnafifi** [comment]
Hi, thanks for your message. 

I think if you are interesting in image retouching through Hue modification, modifying the XYZ values are not the right way as the CIE XYZ does not have no direct equivalent to the hue channel found in color spaces like HSV. The CIE XYZ color space is a device-independent color space that represents colors based on human perception. These components do not directly correspond to hue, saturation, or value. Instead, they provide information about the amount of the three primary colors (X, Y, and Z) needed to represent a particular color.

I hope this explanation helps clarify the distinction.

**Comment by a2108870** [comment]
Thank you for your patient explanation.
