### ISSUE TITLE
Question about XYZ to sRGB conversion details

### ISSUE THREAD

**Issue by a2108870** [mahmoudnafifi/CIE_XYZ_NET#7]
Hi Mahmoud,

Thank your valuable work. I have downloaded the image pairs you provided and I want to further modify some parameters such as brightness, contrast, saturation, etc. to augment the number of traing image pairs.
I was wondering if you could provide more details on the XYZ to sRGB conversion process. Specifically, I'm interested in knowing which parameters in the Adobe Camera RAW software development kit you adjusted and how these parameters were adjusted.
Thank you very much for your time and attention.

**Comment by mahmoudnafifi** [comment]
Hi, thanks for your message.

We have rendered the DNG files using the default settings in Adobe Camera Raw. Regrettably, I just realized that we only offer the XYZ/JPEG pairs. However, you may be able to obtain the corresponding DNG files from the 5K dataset.

**Comment by a2108870** [comment]
Thank you very much！
