### ISSUE TITLE
PSNR calculation

### ISSUE THREAD

**Issue by DY112** [mahmoudnafifi/CIE_XYZ_NET#8]
Hi @mahmoudnafifi. Thanks for your great work.
I have some question about XYZ colorspace & PSNR calculation.

First, I searched for the range of the XYZ color space because the PSNR calculation requires the maximum value of the signal.
As you can see in Professor Michael S. Brown's slide, there is a range of XYZ values:
<img width="633" alt="image" src="https://github.com/mahmoudnafifi/CIE_XYZ_NET/assets/24367643/3b84fa0e-ed7a-4e59-880a-05f3548827c4">
As far as I know, these three functions represent the XYZ mixing coefficients (XYZ values) for representing the color of light corresponding to a particular single wavelength.

In one [article](https://www.sttmedia.com/colormodel-xyz), the author says that the values of XYZ are [X-95.047, Y-100, Z-108.883].
I believe Michael's slide is correct, but is there another version of CIE XYZ that I'm not aware of?

Second, if so, how can I calculate the PSNR of a CIE XYZ image?
The channel ranges in CIE XYZ are all different. How did you calculate the PSNR calculated in table 1 of the CIE XYZnet paper?

**Comment by mahmoudnafifi** [comment]
Hi, thanks for your question. We used xyz: x = X / (X+Y+Z), y = y / (X+Y+Z), z = z / (X+Y+Z). That gives us normalized values (0,1) and then PSNR can be used directly without any modifications. You can read more about the conversion from raw to xyz in the supp materials of this paper: https://arxiv.org/pdf/2011.11890.pdf (sec D.1 and D.2). Hope this helps!

**Comment by DY112** [comment]
Thanks! 😁
